### PR TITLE
Feature: spring adapter

### PR DESCRIPTION
**Pull request by aburmeis**
As described in #158 here is a new adapter for spring framework for client side request and response validation using `RestTemplate` and automatic request and response validation for MockMVC controller tests.

### CODE REVIEW

**Comment by aburmeis** [comment]
I tried to write some documentation but I am not clear how to generate/verify the docs on my local machine. Maybe someone could add this to the Contributing section of the readme.

**Comment by llfbandit** [comment]
Thanks for your work! 👍 

Documentation is located in `docs/operation-validator-adapters/`. Simply copy an existing <adapter>.md file to `spring.md` and add your own info.
Documentation is auto-generated and will when this PR will be merged.

**Comment by aburmeis** [comment]
@llfbandit Thanks, the `spring.md` is already there! I would like to have a look on the generated documentation upfront but if this is not possible I can wait.

**Comment by aburmeis** [comment]
@llfbandit Any chance to get this merged and released in the near future?

**Comment by llfbandit** [comment]
Hi,
Seems good to to me.
I'll try to find some time this week-end to tackle current reported issues and make a new release with this adapter.

Thanks again for your patience, this project needs much more time that I currently can provide.

**Pull request merged**
