### PR TITLE
adding rest-assured adapter

### PR DESCRIPTION
**Pull request by erosb**
This PR adds a RestAssured adapter. This is useful for improving RestAssured-based API tests which verify that the SUT endpoint conforms to a given OpenAPI definition.

### CODE REVIEW

**Comment by bdremynoel** [comment]
Hi,

Thanks for opening this request.
Can you conform to the other adapters by using `DefaultRequest` and `DefaultResponse` builders in an abstract class ?
This will keep usage consistency between all adapters and will eliminate bugs by using internals maps and collections provided by the builders. that said, this looks pretty good to me.

Also, you can copy/paste Servlet test to complete this PR. This should be not much further work to achieve this.

**Comment by erosb** [comment]
Hello, yes, done. Added 2 tests, one for the Request, one for the Response adapter. One attribute missing is that for the request, I didn't test if the correct HTTP method is returned by `RestAssuredRequest#getMethod()` (this turned out to be a quirky), but otherwise the line coverage is 94% and 100% on the added classes. I hope it is ok.

**Comment by erosb** [comment]
Hello @bdremynoel , do you plan to you merge this PR by any chance?

**Comment by erosb** [comment]
Hello @bdremynoel , do you have any update on this, please?

**Comment by llfbandit** [comment]
Hi,

sorry my time is very limited for now.

Can you conform to the other adapters by using DefaultRequest and DefaultResponse builders in an abstract class ?
This will keep usage consistency between all adapters and will eliminate bugs by using internals maps and collections provided by the builders.
Also, this will avoid iterations/convertions on sub-objects.

**Comment by erosb** [comment]
Thanks for merging the PR. I wrote a blog post about how we use this library in our project: https://hazelcast.com/blog/contract-first-development-using-restassured-and-openapi/

**Pull request merged**
