### PR TITLE
fix(validateBody): validate req/res body using media types with params

### PR DESCRIPTION
**Pull request by borjacampina**
I know there is no charset (or any) parameter required for "application/json" media type (http://www.iana.org/assignments/media-types/application/json) and the UTF-8 is the default encoding (UTF-8, UTF-16.. https://www.ietf.org/rfc/rfc4627.html#section-3) but if an parameter is given like "application/json; charset=UTF-8" I think OperationValidator is not working properly.

In bodyValidator creation process, the validators are stored using their complete media type value as a key map (ex: "application/json; charset=UTF-8")
https://github.com/openapi4j/openapi4j/blob/0309aa57ae50f58bc566828e773583158fdcc317/openapi-operation-validator/src/main/java/org/openapi4j/operation/validator/validation/OperationValidator.java#L317

but when we are validating a body, we only use the type only ("appplication/json") part as key, without parameters, so we cannot recover the stored validator.

https://github.com/openapi4j/openapi4j/blob/0309aa57ae50f58bc566828e773583158fdcc317/openapi-operation-validator/src/main/java/org/openapi4j/operation/validator/validation/OperationValidator.java#L230

### CODE REVIEW

**Comment by llfbandit** [comment]
Hi,

I'm confused with what you're trying to achieve here.
Media types in OAS are following [rfc6838](https://tools.ietf.org/html/rfc6838).
So, you should not specify a charset on application media types, this is reserved for text types registration.

Without any change, this should already work: `Content-Type: application/json; charset=UTF-8` and pass the validation by only specifying `application/json` media type in your API description.

If your use case is about restricting the media type combined with encoding, I think we should let as it is to apply the given restriction.

I may be wrongly analyzed your need, please give more input about your issue in that case.
Thanks.

**Comment by borjacampina** [comment]
Thank you @llfbandit. I have updated the example/test case with a rfc6838 media type example: "text/plain; charset=iso-8859-1".

Let me comment the two lines of code shared before:

BodyValidator creation step: it is stored in validators map using full media type value: "text/plain; charset=iso-8859-1"
https://github.com/openapi4j/openapi4j/blob/0309aa57ae50f58bc566828e773583158fdcc317/openapi-operation-validator/src/main/java/org/openapi4j/operation/validator/validation/OperationValidator.java#L317

```
// map representation, <key> = <value>
"text/plain; charset=iso-8859-1" = <BodyValidator instance>
```

BodyValidator.validate step: we recover the BodyValidator from validators map not using the origin full media type value because ContentType.getTypeOnly returns "text/plain" (without charset parameter) so the original BodyValidator cannot be recovered

https://github.com/openapi4j/openapi4j/blob/0309aa57ae50f58bc566828e773583158fdcc317/openapi-operation-validator/src/main/java/org/openapi4j/operation/validator/validation/OperationValidator.java#L230

**Comment by llfbandit** [comment]
Oh I see, I miss the line `230` in your description.
And... This is where the bug is. We should not truncate each `Content-Type` header without a smarter logic.

We should detect:
- text/whatever media type to apply the restriction on charset (if any).
- the wildcard for `video/*`, `image/*`, etc. media types too (out of scope of the issue but still).

**Comment by llfbandit** [comment]
Related to #53 
PR #54 is treating both concerns.

Thank you for your work! 👍 
Feel free to (re-open) the issue if it doesn't fully match your proposed changes.

**Pull request closed without merging**
