### PR TITLE
Collect warning and info logs from oneof and anyof discriminators

### PR DESCRIPTION
**Pull request by smhc**
Also suppresses the 'anyOf' and 'oneOf' crumbs to accurately navigate data.

### CODE REVIEW

**Comment by smhc** [comment]
If you don't like the suppression of 'anyOf' and 'oneOf' crumbs, could we treat those (and other non-properties) differently? It seems the 'crumbs' is serving two purposes - the path in the schema and the path in the data.

I think there should either be two sets of crumbs (one for data, one for schema) or the crumbs should indicate which parts are schema vs data. e.g something like:

"<body>.animal.<oneOf>.cat.name"

Thus you can navigate either the data or the schema using the one crumb, by ignoring the "<xx>" properties which are schema related.

**Comment by llfbandit** [comment]
I agree, that could be a quick workaround for your needs. I'll check what can be done widely tomorrow.

Also, I though today about a tracing system to collect the resulting schema but I had not enough time because of struggling with sonatype (again) when releasing 0.8.

**Comment by smhc** [comment]
> About the requested changes in the current PR, I don't want to deal to much with breadcrumb during validation process. This should stay a no brainer (maintenance speaking).

Note that the requested changes in the PR do two things:

1. Fix logging of validation INFO and WARN results for anyof/oneof for the matching schema. They were previously being discarded.
2. Suppress the anyof/oneof "property" in the breadcrumb.

You may wish to change the way point 2 is done, but I believe point 1 is a bug fix that needs to be merged (or reworked if you wish).

It isn't too difficult from a maintenance perspective to have this special treatment for breadcrumbs - essentially only the 'property' validator should be used for the "data" crumb. Everything else is part of the 'schema' crumb.

**Comment by llfbandit** [comment]
Please follow up this PR in #79

**Pull request closed without merging**
